### ISSUE TITLE
Empty descriptions on the package index webpage

### ISSUE THREAD

**Issue by olaure01** [coq/opam-coq-archive#1368] opened 2020-08-04 20:56 UTC
On the [package index page](https://coq.inria.fr/opam/www/), many packages have empty descriptions `""` (see for example `coq-ails`, `coq-alea`, etc.).

**Comment by palmskog** [comment] 2020-08-04 20:59
Thanks for reporting, but this is a duplicate of #691, so feel free to contribute to the discussion there.

**Closed by palmskog** 2020-08-04 20:59 UTC
