### ISSUE TITLE
Coq package index omits synopsis for many packages

### ISSUE THREAD

**Issue by palmskog** [coq/opam-coq-archive#691] opened 2019-05-16 16:54 UTC
After the upgrade to OPAM 2, many descriptions/synopses of packages in the [Coq package index](https://coq.inria.fr/opam/www/) only consist of `""`. This could be due to the split of `description` into both `synopsis` (always one line) and `description` (multiple lines).

**Comment by mattam82** [comment] 2019-09-30 14:10
Right, I'll see if I can fix that, @gares which script should I look at?

**Comment by Zimmi48** [comment] 2019-09-30 14:25
@mattam82 It seems from your question that you are considering a software fix rather than a content fix?

**Comment by mattam82** [comment] 2019-09-30 14:49
Yes, it should accept multiline descriptions as well.

**Comment by gares** [comment] 2019-09-30 15:14
The conversion was done by `opam admin upgrade`, see https://opam.ocaml.org/blog/opam-2-0-0-repo-upgrade-roadmap/#Advice-for-package-maintainers

I suspect that the problem is the following:
- in opam 1 there was just one field (a file actually) and archive2web was displaying that
- with the conversion to opam 2 the file was split into two fields, synopsis and description with archive2web only displaying one of the two
- finally archive2web was rewritten in OCaml by @maximedenes so maybe things change again

IMO, when we see `""` it is the synopsys that is empty, and it can be, but maybe the description field is not empty.

**Comment by mattam82** [comment] 2019-09-30 15:22
In "" cases the synopsis is not empty but the description is multiline.

**Comment by gares** [comment] 2019-09-30 15:22
We looked with Maxine, it seems that the website deployed is not the new one, but al old copy (before the archive2html thing was rewritten)

**Comment by gares** [comment] 2019-09-30 15:28
it looks like this Makefile of this repo still calls yamlpp, while it should not anymore

**Comment by mattam82** [comment] 2019-09-30 17:45
I see, should be easily fixable tomorrow then :)

**Comment by silene** [comment] 2021-06-22 12:20
Tentatively closing, as the website now uses the new code.

**Closed by silene** 2021-06-22 12:20 UTC
