### ISSUE TITLE
Outdated tar.gz

### ISSUE THREAD

**Issue by clarus** [coq/opam-coq-archive#10] opened 2015-08-11 10:30 UTC
This issue was raised by @mlasson. The problem is that the [`tar.gz` archive](https://coq.inria.fr/opam/core-dev/archives/coq.dev+opam.tar.gz) of `coq.dev` is two months old. As mentioned by @silene and @gares, the generation of `tar.gz` could be disabled, using:

```
opam admin make --index
```

instead of:

```
opam admin make
```

I am OK with that. Here are the links of the directories which would (should?) become empty:
- [released/archives](https://coq.inria.fr/opam/released/archives/) (maybe we can keep this one)
- [extra-dev/archives](https://coq.inria.fr/opam/extra-dev/archives/)
- [core-dev/archives](https://coq.inria.fr/opam/core-dev/archives/)

**Comment by gares** [comment] 2015-08-15 09:06
Should be fixed by now, best

**Comment by clarus** [comment] 2015-08-15 16:43
I tested and it did not work for me. I think the problem is that the `archives` folders still contain the `tar.gz`.

**Comment by gares** [comment] 2015-08-15 17:20
Could be, indeed I tested it after a git clean -dfx.

If you confirm it works (after a clean) then the problem is that we should run (once) a git clean on the web server (I don't have access...)

**Comment by clarus** [comment] 2015-08-16 08:18
OK! The problem is that I do not know how to have access either (that is why I was lazily reporting bugs instead of fixing).

**Comment by gares** [comment] 2016-09-07 18:27
@maximedenes you should have access to the server.  Either we mirror (and keep updated) the tarballs, or we don't and remove the directory.

**Comment by mattam82** [comment] 2018-02-09 12:26
Looks fixed to me, the archives are built correctly it seems (at least they're not outdated). Feel free to reopen if not.

**Closed by mattam82** 2018-02-09 12:26 UTC
