### ISSUE TITLE
is there a coq-mtac for 8.6 yet?

### ISSUE THREAD

**Issue by cartazio** [coq/opam-coq-archive#169] opened 2017-07-22 18:25 UTC

**Comment by gares** [comment] 2017-07-25 12:10
I guess @beta-ziliani knows better

**Comment by beta-ziliani** [comment] 2017-07-25 12:41
I guess we should do a package for MetaCoq (Mtac's successor). The problem is that we're still solving some issues there. What do you need to do @cartazio ?

**Comment by cartazio** [comment] 2017-07-25 21:01
@beta-ziliani imperfect isn't the obstacle to trying stuff out :) 
I'm on a massive yak shave to compare the proof automation / modelling tools of the various CIC related theorem provers and friends for some work projects that would benefit from light weight formal methods and such. So mostly experimentation.  Currently i'm mostly doing some light weight modelling in agda, but the better automation tooling around coq and lean has appeal, and i'm trying to limit myself to only easy to install coq tools :) 

what sort of issues are a barrier to having an opam release / feeling good about users poking at it?

**Comment by herbelin** [comment] 2017-07-25 21:13
@beta-ziliani: I agree with @cartazio. The best is the ennemy of good. Even if the current version has some "issues", feedback and interaction with others might help to better see how to fix the issues and where to put one's own energy to go next.

You made a very good job based on very interesting ideas and it seems enough to be already used by more people. Put the appropriate cautions making clear the current state and what you are not satisfied about yet.

**Comment by cartazio** [comment] 2017-07-25 21:54
I promise to give tickets on any problem and all of them

**Comment by beta-ziliani** [comment] 2017-07-27 13:06
Alright, I'll try to do this asap.

**Comment by mattam82** [comment] 2017-09-13 12:38
@beta-ziliani ping :)

**Comment by beta-ziliani** [comment] 2017-09-14 12:25
sorry, we've just been under a heavy development (including renaming!) of Mtac2. I promise there will be a package "soon".

**Comment by beta-ziliani** [comment] 2017-12-01 12:05
@cartazio sorry for the long delay, but I finally did the packaging. As soon as it is merged, you should be able to access it. Let me know if you need any help.

**Comment by ejgallego** [comment] 2019-06-13 12:38
This is stale, coq-mtac2 is maintained.

**Closed by ejgallego** 2019-06-13 12:38 UTC
