### ISSUE TITLE
Issues in compiling coq:extraction:lwt:ocaml and coq:concurrency:pluto

### ISSUE THREAD

**Issue by herbelin** [coq/opam-coq-archive#26] opened 2015-11-16 21:17 UTC
Hi, I don't know if this is the right place for reporting bugs in installing opam packages for Coq, but I fell on two problems:

In installing coq:extraction:lwt:ocaml, I got an "Unbound value Lwt.fail_with" (script follows below).

In trying to install coq:concurrency:pluto, I got: "Your request can't be satisfied: - No package matches coq:concurrency:pluto".

Debugging output (which I don't know how to interpret accurately) gives:

```
00:01.386  031289  HEURISTIC               state-of-request: install:(coq%3aconcurrency%3asystem & coq & camlp5 & base-unix & base-threads & base-bigarray) remove:() upgrade:(coq%3aconcurrency%3apluto) criteria:"-removed,-notuptodate,-changed" CONFLICT!
00:01.386  031289  CUDF                    resolve request=install:(coq%3aconcurrency%3asystem & coq & camlp5 & base-unix & base-threads & base-bigarray) remove:() upgrade:(coq%3aconcurrency%3apluto) criteria:"-removed,-notuptodate,-changed"
00:01.386  031289  CLIENT                  conflict!
Your request can't be satisfied:
  - No package matches coq:concurrency:pluto.
```

---

Report for coq:extraction:lwt:ocaml is

```
.#=== ERROR while installing coq:extraction:lwt:ocaml.dev ======================#
# opam-version 1.2.0
# os           linux
# command      make -j1
# path         /home/herbelin/COQ/git/v8.5/opam/system/build/coq:extraction:lwt:ocaml.dev
# compiler     system (3.12.1)
# exit-code    2
# env-file     /home/herbelin/COQ/git/v8.5/opam/system/build/coq:extraction:lwt:ocaml.dev/coq:extraction:lwt:ocaml-1222-7afd23.env
# stdout-file  /home/herbelin/COQ/git/v8.5/opam/system/build/coq:extraction:lwt:ocaml.dev/coq:extraction:lwt:ocaml-1222-7afd23.out
# stderr-file  /home/herbelin/COQ/git/v8.5/opam/system/build/coq:extraction:lwt:ocaml.dev/coq:extraction:lwt:ocaml-1222-7afd23.err
### stdout ###
# ocamlbuild extractionLwt.cma extractionLwt.cmxa -use-ocamlfind -package lwt,lwt.unix,num
# ocamlfind ocamldep -package lwt,lwt.unix,num -modules extractionLwt.ml > extractionLwt.ml.depends
# ocamlfind ocamlc -c -package lwt,lwt.unix,num -o extractionLwt.cmo extractionLwt.ml
# + ocamlfind ocamlc -c -package lwt,lwt.unix,num -o extractionLwt.cmo extractionLwt.ml
# File "extractionLwt.ml", line 14, characters 13-26:
# Error: Unbound value Lwt.fail_with
# Command exited with code 2.
### stderr ###
# make: *** [default] Erreur 10
```

**Comment by clarus** [comment] 2015-11-16 21:39
Thanks for this report! We can also report bugs on each project's bug tracker. The `coq:extraction:lwt:ocaml` is one of my development packages (I am planning to move it to [clarus/coq-repo](https://github.com/clarus/coq-repo) after the `:` vs `-` renaming), thus there may be many bugs. The problem with `coq:concurrency:pluto` is surprising. What does the `opam list` command gives you in both cases?

**Comment by herbelin** [comment] 2015-11-16 21:40
Another problem in installing coq:io:system:ocaml.2.3.0: List.iteri is not found, so probably a dependency missing on the version of OCaml.

**Comment by herbelin** [comment] 2015-11-16 21:46
opam list gives

    # Installed packages for system:
    base-bigarray                    base  Bigarray library distributed with the OCaml compiler
    base-threads                     base  Threads library distributed with the OCaml compiler
    base-unix                        base  Unix library distributed with the OCaml compiler
    camlp4                    4.01+system  Camlp4 is a system for writing extensible parsers for programmin
    camlp5                           6.14 (pinned)  Preprocessor-pretty-printer of OCaml
    coq                         8.5~beta2  Formal proof management system.
    coq:concurrency:system            dev  Experimental library to write concurrent applications in Coq.
    coq:error-handlers                dev  Simple and robust error handling functions.
    coq:extraction:sys:ocaml          dev  Interface to the native OCaml Sys library.
    coq:function-ninjas               dev  Simple functional combinators.
    coq:list-plus                     dev  More functions on lists.
    coq:list-string                 2.1.0  Strings implemented as lists.
    lwt                             2.4.5  A cooperative threads library for OCaml
    ocamlfind                       1.5.6  A library manager for OCaml

**Comment by clarus** [comment] 2015-11-16 21:52
Thanks, I added the commits [f693c404ab343b4eb0726a8c8e59f18dedd16ae0](https://github.com/coq/opam-coq-archive/commit/f693c404ab343b4eb0726a8c8e59f18dedd16ae0) and [202b9dd145f37a7adb0930eb730a5f4eabe0f8fc](https://github.com/clarus/coq-repo/commit/202b9dd145f37a7adb0930eb730a5f4eabe0f8fc) for the `List.iteri` problem.

**Comment by clarus** [comment] 2015-11-16 21:55
OK for the `opam list`, I am currently trying to reproduce the error (compiling...).

**Comment by clarus** [comment] 2015-11-16 23:29
What are your OPAM and OCaml versions? What does `opam repo` says?

**Comment by herbelin** [comment] 2015-11-17 11:10
As indicated above, OPAM 1.2.0 and OCaml 3.12.1 (system).

Possible steps to reproduce are (in tcsh):
    setenv MYROOT /home/herbelin/COQ/git/v8.5/opam
    setenv CAMLP5VERSION 6.14
    setenv COQVERSION 8.5~beta2
    opam init --root $MYROOT --no-setup
    opam install --root $MYROOT camlp5=$CAMLP5VERSION
    opam pin --root $MYROOT add camlp5 $CAMLP5VERSION
    opam repo --root $MYROOT add core-dev https://coq.inria.fr/opam/core-dev #1
    opam install --root $MYROOT coq=$COQVERSION
    opam pin --root $MYROOT add coq $COQVERSION
    opam install --root $MYROOT coq:concurrency:pluto  #fail
    opam repo --root $MYROOT add extra-dev https://coq.inria.fr/opam/extra-dev
    opam install --root $MYROOT coq:extraction:lwt:ocaml #fail


Note that I prepared this archive when beta2 was still in released, so I had at this time

    opam repo --root $MYROOT add released https://coq.inria.fr/opam/released

instead of line #1. I did not replay using core-dev, but I don't see what it would change, since the errors occur also when core-dev is added.

**Comment by clarus** [comment] 2015-11-17 12:14
Ok, I haven't seen the version of OPAM and OCaml. I tried to reproduce your settings, and I got:

    The following dependencies couldn't be met:
      - coq:concurrency:pluto -> coq:concurrency:proxy
    Your request can't be satisfied:
      - coq:concurrency:proxy is not available because it requires OCaml >= 4.02.0.

    No solution found, exiting

Thus I get a clear error message explaining why `coq:concurrency:pluto` cannot be installed. It may be that I use OPAM `1.2.2` instead of `1.2.0`.

**Comment by herbelin** [comment] 2015-11-17 12:45
I tried installing aspcud and I then got the same message as you. So this is not an opam issue, but a solver issue. So, this seems to definitively mean that opam default solver should really be not advised (considering that I had various other problems with the default solver not finding interesting solutions).

**Comment by herbelin** [comment] 2015-11-17 12:52
On the other side, for coq:extraction:lwt:ocaml, with aspcud, I get:

    The following actions will be performed:
     - install   base-no-ppx.base                      [required by lwt]
     - upgrade   lwt from 2.4.5 to 2.4.6               [required by coq:extraction:lwt:ocaml]
     - install   coq:extraction:lwt:ocaml.dev

while with --no-aspcud, I get:

    The following actions will be performed:
     - install   coq:extraction:lwt:ocaml.dev

So, here, aspcud is giving a more convulate choice. So what to think?

[And in both cases, compilation fails on Lwt.fail_with.]

**Comment by clarus** [comment] 2015-11-17 13:29
Yes, `aspcud` seems not to be an option. Here is the issue on OPAM: [opam#1267](https://github.com/ocaml/opam/issues/1267). We will have to document it and ask for each bug report if the user is using `aspcup`.

For the `coq:extraction:lwt:ocaml` example, actually OPAM also tries to do *some* updates during installation. For more details, see [solver preferences](http://opam.ocaml.org/doc/Specifying_Solver_Preferences.html#Defaultpreferencesforaninstall).

**Comment by herbelin** [comment] 2015-11-17 14:46
But what to do for non-expert users? What out-of-the-box solution to propose to Coq users so that using opam is a benefit and not a complication?

**Comment by clarus** [comment] 2015-11-17 15:01
We ask to install both `opam` and `aspcud` for now, and report this "bug" on the OPAM project.

**Comment by clarus** [comment] 2015-11-17 15:09
I agree that OPAM is not perfect, but it already works quite reasonably and there is the OCaml community supporting it, so I guess that on the long run this kind of problems will be solved.

**Comment by herbelin** [comment] 2015-11-17 18:34
I think I'm sharing your enthusiasm. Despite the complexity, there is something fascinating in a tool like opam and I'm looking forward how it will be adopted by users in general (with the question of what to do with the MML/AFP-style editorial model of user contributions still open).

**Comment by relrod** [comment] 2016-10-18 04:20
> `# Error: Unbound value Lwt.fail_with`

No idea if you worked past this or not, but since the issue is still open, I'll throw this here because I just ran into the same thing:

It seems `Lwt.fail_with` wasn't added (according to the API docs) until *after* LWT 2.4.5. So make sure your LWT is semi-recent.

**Comment by mattam82** [comment] 2018-02-09 12:38
coq-io and coq-io-system-ocaml on 8.7 seem to work fine. I don't have time to investigate the 8.6/8.5 situation now. However still in 8.7 coq-concurrency-system fails (hence coq-concurrency-pluto cannot be installed). @clarus can you have a look?

**Comment by clarus** [comment] 2019-08-15 15:40
@mattam82 `coq-io` and `coq-io-system-ocaml` seem to work fine now, as well as `coq-concurrency-pluto`. @herbelin @relrod Should we now close this issue?

**Comment by herbelin** [comment] 2019-08-27 14:33
Yes, it can be closed for me.

**Comment by clarus** [comment] 2019-08-27 14:44
OK thanks!

**Closed by clarus** 2019-08-27 14:44 UTC
